---
name: "concurrency-issue-trigger"

# Build and release all artifacts is either triggered manually or on the first day of the month to 
# ensure all artifacts are up-to-date with security and other patches to these distributions
on:
  workflow_dispatch:

jobs:
  build-debian-stretch:
    uses: josmartin/demo-release-action/.github/workflows/concurrency-issue-workflow-call.yaml@main
    with: 
      dist-base: debian
      dist-tag: stretch

  build-debian-buster:
    uses: josmartin/demo-release-action/.github/workflows/concurrency-issue-workflow-call.yaml@main
    with: 
      dist-base: debian
      dist-tag: buster

  build-debian-bullseye:
    uses: josmartin/demo-release-action/.github/workflows/concurrency-issue-workflow-call.yaml@main
    with: 
      dist-base: debian
      dist-tag: bullseye

  build-ubuntu-bionic:
    uses: josmartin/demo-release-action/.github/workflows/concurrency-issue-workflow-call.yaml@main
    with: 
      dist-base: ubuntu
      dist-tag: bionic

  build-ubuntu-focal:
    uses: josmartin/demo-release-action/.github/workflows/concurrency-issue-workflow-call.yaml@main
    with: 
      dist-base: ubuntu
      dist-tag: focal

  build-ubuntu-hirsute:
    uses: josmartin/demo-release-action/.github/workflows/concurrency-issue-workflow-call.yaml@main
    with: 
      dist-base: ubuntu
      dist-tag: hirsute