---
name: "current"
# This workflow keeps the "current" release artifacts up-to-date on a periodic basis

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * * *'

jobs:
  current-release:
    name: "Current Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"

      - name: "Build & test"
        run: |
          DOCKER_BUILDKIT=1 docker build --output type=local,dest=. --build-arg NAME=relobj1.test .
          DOCKER_BUILDKIT=1 docker build --output type=local,dest=. --build-arg NAME=relobj2.test .
          DOCKER_BUILDKIT=1 docker build --output type=local,dest=. --build-arg NAME=relobj3.test .
      - name: "Get License to release under"
        shell: bash
        run: |
          wget -q -O COPYING  'https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=COPYING;hb=HEAD'
          wget -q -O LICENSES 'https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=LICENSES;hb=HEAD'
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "current"
          prerelease: false
          title: "Current Release Artifacts"
          files: |
            build/*.test
            COPYING
            LICENSES