---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    uses: josmartin/demo-release-action/.github/workflows/build-and-release.yaml@main
    with: 
      dist-base: ubuntu
      dist-tag: focal