---
name: "release-debian-bullseye"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  release-debian-bullseye:
    uses: josmartin/demo-release-action/.github/workflows/build-and-release.yaml@main
      with: 
        dist-base: debian
        dist-tag: bullseye