---
name: "release-debian-stretch"

on:
  workflow_dispatch:

jobs:
  build:
    uses: josmartin/demo-release-action/.github/workflows/build-and-release.yaml@main
    with: 
      dist-base: debian
      dist-tag: stretch
