---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"

      - name: "Build & test"
        shell: bash
        run: |
          DOCKER_BUILDKIT=1 docker build --output type=local,dest=. --build-arg NAME=obj1.test .
          DOCKER_BUILDKIT=1 docker build --output type=local,dest=. --build-arg NAME=obj2.test .
          DOCKER_BUILDKIT=1 docker build --output type=local,dest=. --build-arg NAME=obj3.test .

      - name: "Get License to release under"
        shell: bash
        run: |
          wget -q -O COPYING  'https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=COPYING;hb=HEAD'
          wget -q -O LICENSES 'https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=LICENSES;hb=HEAD'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/*.test
            COPYING
            LICENSES
            